In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
import os
from indicnlp import common
from indicnlp.tokenize import indic_tokenize

In [3]:
from transformers import AutoTokenizer

/home/thasin/class-projects/LLM-project/.venv/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
tokenizer=AutoTokenizer.from_pretrained("google-T5/T5-base")

In [5]:
data=pd.read_csv("/home/thasin/class-projects/LLM-project/Sentence pairs in English-Hindi - 2025-02-13.tsv",sep="\t",header=None,names=["SrcSentenceID","SrcSentence","DstSentenceID","DstSentence"])

In [6]:
data.head()

SrcSentenceID                              SrcSentence  DstSentenceID  \
0           1282                       Muiriel is 20 now.         485968   
1           1282                       Muiriel is 20 now.        2060319   
2           1294  Education in this world disappoints me.         485564   
3           1302                       That won't happen.        2060320   
4           1308                              I miss you.        2060321   

                                   DstSentence  
0             म्यूरियल अब बीस साल की हो गई है।  
1                   म्यूरियल अब बीस साल की है।  
2  मैं इस दुनिया में शिक्षा पर बहुत निराश हूँ।  
3                              वैसा नहीं होगा।  
4                 मुझें तुम्हारी याद आ रही है।

In [7]:
data["DstSentence"]=data["DstSentence"].apply(lambda x: indic_tokenize.trivial_tokenize(x,lang="hi"))

In [8]:
data["DstSentence"]

0              [म्यूरियल, अब, बीस, साल, की, हो, गई, है, ।]
1                      [म्यूरियल, अब, बीस, साल, की, है, ।]
2        [मैं, इस, दुनिया, में, शिक्षा, पर, बहुत, निराश...
3                                    [वैसा, नहीं, होगा, ।]
4                    [मुझें, तुम्हारी, याद, आ, रही, है, ।]
                               ...                        
13177            [क्या, आपके, पास, सब्ज़ी, -, चावल, है, ?]
13178            [क्या, आपके, पास, सब्ज़ी, -, चावल, है, ?]
13179            [क्या, आपके, पास, सब्ज़ी, -, चावल, है, ?]
13180            [क्या, आपके, पास, सब्ज़ी, -, चावल, है, ?]
13181              [मुझे, यह, साइकिल, अब, भी, पसंद, है, ।]
Name: DstSentence, Length: 13182, dtype: object

In [9]:
Nd=max(list(data["DstSentence"].apply(len)))

In [10]:
Nd

67

In [11]:
data["SrcSentence"]=data["SrcSentence"].apply(lambda x: tokenizer.tokenize(x))

In [12]:
data["SrcSentence"]

0                        [▁Mu, i, riel, ▁is, ▁20, ▁now, .]
1                        [▁Mu, i, riel, ▁is, ▁20, ▁now, .]
2        [▁Education, ▁in, ▁this, ▁world, ▁disappoint, ...
3                          [▁That, ▁won, ', t, ▁happen, .]
4                                     [▁I, ▁miss, ▁you, .]
                               ...                        
13177    [▁Do, ▁you, ▁have, ▁some, ▁curry, ▁and, ▁some,...
13178    [▁Do, ▁you, ▁have, ▁curry, ▁and, ▁some, ▁rice, ?]
13179    [▁Do, ▁you, ▁have, ▁any, ▁curry, ▁with, ▁rice, ?]
13180          [▁Do, ▁you, ▁have, ▁curry, ▁with, ▁rice, ?]
13181              [▁I, ▁still, ▁love, ▁this, ▁bicycle, .]
Name: SrcSentence, Length: 13182, dtype: object

In [13]:
Ns=max(list(data["SrcSentence"].apply(len)))

In [14]:
Ns

68

In [15]:
Vs = tokenizer.get_vocab()

In [16]:
Vs

{'RP': 6294,
 '▁chronological': 31803,
 '▁Kaffee': 14854,
 '▁Libya': 24533,
 '▁insert': 8722,
 '▁Dawn': 21903,
 '▁overall': 1879,
 '▁cogn': 23179,
 'pleasantly': 29183,
 'detecting': 29782,
 '▁broad': 4358,
 'pati': 7768,
 '▁Gorgeous': 26448,
 '▁fragrance': 15430,
 '▁perspective': 3503,
 '▁exhaust': 10685,
 '▁Yorkshire': 19830,
 'aurez': 17424,
 '▁abortion': 20526,
 '▁Holly': 24205,
 '▁encode': 23734,
 '▁détach': 31843,
 '▁RFID': 30069,
 'education': 29117,
 '▁half': 985,
 'EACH': 29027,
 'vage': 11515,
 'vul': 12388,
 '▁canalisation': 27714,
 '▁candy': 11617,
 'Dezvoltare': 26339,
 '▁Lloyd': 21847,
 'occurrence': 16526,
 '▁Pân': 24539,
 '▁cushions': 16790,
 '▁argint': 26090,
 '▁caci': 28352,
 '▁Point': 4564,
 '▁CBS': 19856,
 '▁Hunger': 26049,
 '▁experiment': 5016,
 '▁missed': 4785,
 '▁Vorbereitung': 25510,
 '▁Lamb': 19211,
 '▁diseases': 6716,
 '▁span': 8438,
 '▁Out': 3387,
 '▁tempting': 24873,
 'graphical': 16982,
 'effectuer': 18725,
 'secure': 24875,
 '▁37': 6862,
 '▁Zugriff': 27005

In [17]:
Vd = set()
for tokenized_hindi_sentence in data['DstSentence']:
    Vd.update(tokenized_hindi_sentence)
    
hindi_vocab = dict()

for idx, token in enumerate(Vd):
    hindi_vocab[token] = idx + 3

hindi_vocab["<PAD>"] = 0
hindi_vocab["<SOS>"] = 1
hindi_vocab["<EOS>"] = 2

Vd = hindi_vocab

In [21]:
print(Vd)

{'व्रक्ष': 3, 'टैक्सी': 4, 'निर्धारित': 5, 'आयु': 6, 'दुक्का': 7, 'दिल्ली': 8, 'माईने': 9, 'लक्ष्य': 10, 'वस्\u200dतु': 11, 'खाओगे': 12, 'सिढ़ियों': 13, 'शुभकामनाएँ': 14, 'करेगी': 15, 'किसको': 16, 'धनहीन': 17, 'आखिरी': 18, 'मुझको': 19, 'नासमझ': 20, 'दोपहर': 21, '१९३९': 22, 'मनमोहक': 23, 'स्मिथ': 24, 'स्थान': 25, 'रोबेर्टो': 26, 'माहौल': 27, '१९९६': 28, 'पासवर्ड': 29, 'सर्व': 30, 'मंगल': 31, 'स्वीकारेंगे': 32, 'पूर्वाभास': 33, '१७९९': 34, 'लेखकों': 35, 'सर्वनाश': 36, 'लिहाज़': 37, 'सीड़ियों': 38, 'देखते': 39, 'उड़ाई': 40, 'दिवाई': 41, 'क्षेत्रीय': 42, 'कोलम्बस': 43, 'चपटी': 44, 'उत्तर': 45, 'मास': 46, 'ऐनक': 47, 'राजु': 48, 'उद्यान': 49, 'भुला': 50, 'चक्र': 51, 'इजहार': 52, 'मूँछ': 53, 'मुरम्मत': 54, 'गले': 55, 'मरने': 56, 'रोटी': 57, 'आतंकवादी': 58, 'नंगे': 59, 'मैं': 60, 'पवित्र': 61, 'दौरा': 62, 'चाकलेट': 63, 'बैठूं': 64, 'काबू': 65, 'ग़ुस्से': 66, 'ऊपर': 67, 'चुरा': 68, 'को': 69, 'निचला': 70, 'सुप्रभात': 71, 'भाषण': 72, 'डार्सी': 73, 'ख़ुफ़िया': 74, 'लिया': 75, 'अफ़सोस': 76, 'याकितो

In [18]:
len(Vd)

7072

In [22]:
#jis bhasa me translate krna hai us bhasa me teeno Token chahiye SOS EOS PAD
#jis se translate kr rha hai usme jarurat nhi hai

In [25]:
data.head()

SrcSentenceID                                        SrcSentence  \
0           1282                  [▁Mu, i, riel, ▁is, ▁20, ▁now, .]   
1           1282                  [▁Mu, i, riel, ▁is, ▁20, ▁now, .]   
2           1294  [▁Education, ▁in, ▁this, ▁world, ▁disappoint, ...   
3           1302                    [▁That, ▁won, ', t, ▁happen, .]   
4           1308                               [▁I, ▁miss, ▁you, .]   

   DstSentenceID                                        DstSentence  
0         485968        [म्यूरियल, अब, बीस, साल, की, हो, गई, है, ।]  
1        2060319                [म्यूरियल, अब, बीस, साल, की, है, ।]  
2         485564  [मैं, इस, दुनिया, में, शिक्षा, पर, बहुत, निराश...  
3        2060320                              [वैसा, नहीं, होगा, ।]  
4        2060321              [मुझें, तुम्हारी, याद, आ, रही, है, ।]

In [ ]:
#converting English word to numerical
data['SrcSentence'] = data['SrcSentence'].apply(tokenizer.convert_tokens_to_ids)

#then after that english numeric value will ues as a input in NN afeter converting One hot encoding 

In [28]:
#converting Hindi Sentence to numbers 
def convert_hindi_tokens_to_ids(tokenized_hindi_sentence):
    return [Vd[token] for token in tokenized_hindi_sentence]

In [29]:
data['DstSentence'] = data['DstSentence'].apply(convert_hindi_tokens_to_ids)

In [30]:
data.head()

SrcSentenceID                            SrcSentence  DstSentenceID  \
0           1282     [4159, 23, 14018, 19, 460, 230, 5]         485968   
1           1282     [4159, 23, 14018, 19, 460, 230, 5]        2060319   
2           1294  [2855, 16, 48, 296, 26963, 7, 140, 5]         485564   
3           1302            [466, 751, 31, 17, 1837, 5]        2060320   
4           1308                      [27, 3041, 25, 5]        2060321   

                                         DstSentence  
0  [534, 4063, 4915, 6977, 4549, 2209, 2684, 2210...  
1           [534, 4063, 4915, 6977, 4549, 2210, 353]  
2  [60, 5692, 2909, 6818, 4305, 5133, 1667, 596, ...  
3                            [2964, 3021, 1691, 353]  
4          [2175, 5223, 2099, 4643, 1825, 2210, 353]

In [36]:
X = list(data['SrcSentence'])
Y = list(data['DstSentence'])

X_tensor = [torch.tensor(eng_tokenized_ids) for eng_tokenized_ids in X]
Y_tensor = [torch.tensor(hindi_tokenized_ids) for hindi_tokenized_ids in Y]

X_padded = torch.nn.utils.rnn.pad_sequence(X_tensor,batch_first=True)
Y_padded = torch.nn.utils.rnn.pad_sequence(Y_tensor,batch_first=True)

In [38]:
X_padded.shape

torch.Size([13182, 68])

In [48]:
X_padded[2]

tensor([ 2855,    16,    48,   296, 26963,     7,   140,     5,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0])

In [40]:
Y_padded.shape

torch.Size([13182, 67])

In [47]:
Y_padded[2]

tensor([  60, 5692, 2909, 6818, 4305, 5133, 1667,  596, 3847,  353,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0])

In [94]:
#1 Encoder
#2 Decoder
# 3 attention layer
#then combine all of these

# 1:
#embedding layer does not have bias that will give output in encoder that is first_embedding_layer_output (32100,32)
#the first_embedding_layer_output will go in LSTM layer as a input and give three output 1.encoder output(15,68,32) it is a matrix, 2.final_encoder_ouput[c[0]] vector, 3. final_candidate_cell_output(h1[0]) vector
#encoder box will give two outputs 1.inal_encoder_ouput, 2. final_candidate_cell_output
class Encoder(torch.nn.Module):
    def __init__(self, src_lang_vocab_dim, topic_vector_dim):
        super(Encoder,self).__init__()
        self.first_embedding_layer = torch.nn.Embedding(num_embeddings=src_lang_vocab_dim, embedding_dim=topic_vector_dim)
        self.second_lstm_layer = torch.nn.LSTM(input_size=topic_vector_dim,hidden_size=topic_vector_dim,batch_first=True)
        
    def forward(self,x_padded_mini_batch):
        
        first_embedding_layer_out = self.first_embedding_layer(x_padded_mini_batch)
        encoder_output,(final_encoder_output, final_candidate_cell_output) = self.second_lstm_layer(first_embedding_layer_out)
        
        return encoder_output,(final_encoder_output,final_candidate_cell_output)

In [95]:
test = Encoder(len(X_padded),32)
print(test)

Encoder(
  (first_embedding_layer): Embedding(13182, 32)
  (second_lstm_layer): LSTM(32, 32, batch_first=True)
)


In [96]:
X_padded_mini_batch = torch.randint(0, len(X_padded), (2, 67))

In [98]:
X_padded_mini_batch.shape

torch.Size([2, 67])

In [100]:
encoder_output,(final_encoder_output,final_candidate_cell_output) = test(X_padded_mini_batch)

In [101]:
encoder_output

tensor([[[-0.0573,  0.0515,  0.2148,  ...,  0.1164,  0.2022, -0.0243],
         [ 0.0360,  0.1008,  0.1836,  ...,  0.2001,  0.0750, -0.1845],
         [ 0.1661,  0.0576,  0.2452,  ...,  0.1798, -0.1012, -0.1254],
         ...,
         [-0.0338, -0.0398, -0.1539,  ...,  0.1599,  0.1556,  0.1124],
         [-0.1434,  0.0380, -0.1896,  ...,  0.1584,  0.0336,  0.1614],
         [-0.1264,  0.1295, -0.2540,  ...,  0.3075, -0.1512,  0.3647]],

        [[-0.1598, -0.1809, -0.0657,  ..., -0.1060,  0.1511, -0.0563],
         [-0.1982, -0.1601, -0.1811,  ..., -0.1867,  0.0278, -0.1273],
         [-0.1372, -0.3156, -0.1730,  ...,  0.1487,  0.0402,  0.0430],
         ...,
         [ 0.0570,  0.2141,  0.1376,  ...,  0.0687,  0.0144,  0.0775],
         [-0.1809,  0.1830,  0.1182,  ...,  0.0943,  0.1015, -0.0600],
         [-0.0932,  0.1098, -0.0892,  ..., -0.0270, -0.1084, -0.2366]]],
       grad_fn=<TransposeBackward0>)

In [102]:
encoder_output.shape

torch.Size([2, 67, 32])

In [104]:
final_encoder_output.shape

torch.Size([1, 2, 32])

In [106]:
final_candidate_cell_output.shape  # (num_layers, batch_size, hidden_dim)

torch.Size([1, 2, 32])